const state={data:null,issuers:[],selected:null,view:'radar'};
const $=(s)=>document.querySelector(s), $$=(s)=>[...document.querySelectorAll(s)];
const colors={'IMPROVING':'#1d6b50','STABLE':'#315d7a','DETERIORATING':'#b36b21','STRESS WATCH':'#9d3f35'};
const val=(v,d=1)=>v==null||!Number.isFinite(v)?'N/A':Number(v).toFixed(d);
const money=(v)=>v==null?'N/A':`${v<0?'−':''}$${Math.abs(v/1e9).toFixed(Math.abs(v)>=1e10?0:1)}bn`;
const ratio=(v)=>v==null?'N/A':`${val(v)}x`; const pct=(v)=>v==null?'N/A':`${val(v*100)}%`;
const esc=(s='')=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));

async function boot(){
  wireNav();
  try{const r=await fetch('data/credit.json');if(!r.ok)throw Error(`HTTP ${r.status}`);state.data=await r.json();state.issuers=state.data.issuers.filter(x=>x.latest);state.selected=state.issuers.find(x=>x.ticker==='VZ')||state.issuers[0];
    $('#dataNotice').className='notice ready';$('#dataNotice').textContent=`Verified public-data snapshot · ${state.issuers.length} issuers normalized · no missing values estimated`;
    $('#asof').innerHTML=`DATA SNAPSHOT<br>${new Date(state.data.generated_at).toLocaleDateString(undefined,{year:'numeric',month:'short',day:'2-digit'})}`;
    setupFilters();renderAll();
  }catch(e){$('#dataNotice').textContent='No generated dataset found. Run the refresh pipeline, then serve the web directory.';$('#issuerRows').innerHTML='<tr><td colspan="8" class="empty">Public filing dataset unavailable</td></tr>';$('#scatter').innerHTML='<div class="empty">Run: python run_pipeline.py</div>';}
}
function wireNav(){$$('nav button').forEach(b=>b.onclick=()=>showView(b.dataset.view));window.addEventListener('hashchange',()=>showView(location.hash.slice(1)||'radar'));}
function showView(name){if(!$('#'+name))name='radar';state.view=name;$$('.view').forEach(v=>v.classList.toggle('active',v.id===name));$$('nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===name));history.replaceState(null,'','#'+name);if(state.data){if(name==='dossier')renderDossier();if(name==='mri')renderMRI();if(name==='scenario')renderScenario();}scrollTo(0,0)}
function setupFilters(){[...new Set(state.issuers.map(x=>x.sector))].sort().forEach(x=>$('#sectorFilter').insertAdjacentHTML('beforeend',`<option>${esc(x)}</option>`));['sectorFilter','trendFilter','searchFilter'].forEach(id=>$('#'+id).addEventListener('input',renderRadar));$('#leverageFilter').oninput=()=>{$('#leverageOutput').value=`${Number($('#leverageFilter').value).toFixed(1)}x`;renderRadar()}}
function filtered(){const sector=$('#sectorFilter').value,trend=$('#trendFilter').value,q=$('#searchFilter').value.toLowerCase(),max=+$('#leverageFilter').value;return state.issuers.filter(x=>(sector==='ALL'||x.sector===sector)&&(trend==='ALL'||x.trend===trend)&&(!q||`${x.name} ${x.ticker}`.toLowerCase().includes(q))&&(x.latest.debt_ebitda==null||x.latest.debt_ebitda<=max))}
function choose(ticker,view='dossier'){state.selected=state.issuers.find(x=>x.ticker===ticker)||state.selected;showView(view)}
function renderAll(){renderRadar();renderDossier();renderMRI();renderScenario();showView(location.hash.slice(1)||'radar')}
function renderRadar(){const items=filtered();$('#resultCount').textContent=`${items.length} ISSUERS`;renderScatter(items);$('#issuerRows').innerHTML=items.map(x=>{const m=x.latest;return `<tr data-ticker="${x.ticker}"><td><div class="issuer-name"><b>${esc(x.name)}</b><span>${x.ticker} · ${m.period}</span></div></td><td>${esc(x.sector)}</td><td>${money(m.revenue)}</td><td>${money(m.total_debt)}</td><td>${ratio(m.debt_ebitda)}</td><td>${ratio(m.interest_coverage)}</td><td>${pct(m.fcf_debt)}</td><td><span class="tag ${x.trend.toLowerCase().replace(' ','-')}" style="color:${colors[x.trend]}">${x.trend}</span></td></tr>`}).join('')||'<tr><td colspan="8" class="empty">No issuers match these filters.</td></tr>';$$('#issuerRows tr[data-ticker]').forEach(r=>r.onclick=()=>choose(r.dataset.ticker));const watch=[...items].filter(x=>x.trend==='STRESS WATCH'||x.trend==='DETERIORATING').slice(0,5);$('#watchlist').innerHTML=(watch.length?watch:items.slice(0,5)).map(x=>`<div class="watch-item" data-ticker="${x.ticker}"><div class="top"><b>${x.ticker} · ${esc(x.name)}</b><span class="tag" style="color:${colors[x.trend]}">${x.trend}</span></div><p>${esc(x.signals[0]?.detail||'Review the latest filing evidence and historical trend.')}</p></div>`).join('');$$('.watch-item').forEach(x=>x.onclick=()=>choose(x.dataset.ticker,'mri'))}
function renderScatter(items){const plotted=items.filter(x=>x.latest.debt_ebitda!=null&&x.latest.interest_coverage!=null);if(!plotted.length){$('#scatter').innerHTML='<div class="empty">No comparable leverage and coverage observations.</div>';return}const W=850,H=390,p={l:58,r:25,t:22,b:43},xmax=Math.max(6,...plotted.map(x=>x.latest.debt_ebitda))*1.08,ymax=Math.min(20,Math.max(8,...plotted.map(x=>x.latest.interest_coverage)))*1.08,debts=plotted.map(x=>x.latest.total_debt||0),dmax=Math.max(...debts,1);const sx=x=>p.l+x/xmax*(W-p.l-p.r),sy=y=>H-p.b-Math.min(y,ymax)/ymax*(H-p.t-p.b);let svg=`<svg viewBox="0 0 ${W} ${H}" role="img" aria-label="Issuer leverage and interest coverage scatterplot">`;for(let i=0;i<=5;i++){let y=i*ymax/5;svg+=`<line class="gridline" x1="${p.l}" y1="${sy(y)}" x2="${W-p.r}" y2="${sy(y)}"/><text class="axis-label" x="8" y="${sy(y)+3}">${val(y)}x</text>`}for(let i=0;i<=6;i++){let x=i*xmax/6;svg+=`<line class="gridline" x1="${sx(x)}" y1="${p.t}" x2="${sx(x)}" y2="${H-p.b}"/><text class="axis-label" x="${sx(x)-10}" y="${H-18}">${val(x)}x</text>`}svg+=`<text class="axis-label" x="${W/2-40}" y="${H-3}">DEBT / EBITDA →</text><text class="axis-label" transform="rotate(-90 12 ${H/2})" x="12" y="${H/2}">INTEREST COVERAGE →</text>`;plotted.forEach(x=>{let r=6+Math.sqrt((x.latest.total_debt||0)/dmax)*16,cx=sx(x.latest.debt_ebitda),cy=sy(x.latest.interest_coverage);svg+=`<g data-ticker="${x.ticker}"><circle class="bubble" cx="${cx}" cy="${cy}" r="${r}" fill="${colors[x.trend]}"/><text class="bubble-label" x="${cx+r+3}" y="${cy+3}">${x.ticker}</text></g>`});$('#scatter').innerHTML=svg+'</svg>';$$('#scatter g[data-ticker]').forEach(g=>g.onclick=()=>choose(g.dataset.ticker,'mri'))}
function picker(){return `<div class="issuer-picker"><select aria-label="Select issuer">${state.issuers.map(x=>`<option value="${x.ticker}" ${x===state.selected?'selected':''}>${x.ticker} — ${esc(x.name)}</option>`).join('')}</select></div>`}
function bindPicker(container,renderer){container.querySelector('.issuer-picker select').onchange=e=>{state.selected=state.issuers.find(x=>x.ticker===e.target.value);renderer()}}
function evidence(x,positive){return x.signals.filter(s=>positive?s.severity<0:s.severity>0).map(s=>s.detail).slice(0,3)}
function renderDossier(){const x=state.selected;if(!x)return;const m=x.latest,good=evidence(x,true),weak=evidence(x,false);$('#dossierContent').innerHTML=`<div class="issuer-head"><div><h1 class="page-title">${esc(x.name)}</h1><div class="issuer-meta"><b>${x.ticker}</b><span>${esc(x.sector)}</span><span>${x.country}</span><span>FY ${m.period}</span></div></div>${picker()}</div><div class="summary-strip"><div><small>FUNDAMENTAL TREND</small><strong style="color:${colors[x.trend]}">${x.trend}</strong></div><div><small>LEVERAGE</small><strong>${x.bands.leverage}</strong></div><div><small>COVERAGE</small><strong>${x.bands.coverage}</strong></div><div><small>LIQUIDITY</small><strong>${x.bands.liquidity}</strong></div><div><small>FCF TREND</small><strong>${m.yoy_fcf==null?'Unavailable':m.yoy_fcf>.1?'Improving':m.yoy_fcf<-.1?'Deteriorating':'Stable'}</strong></div></div><div class="evidence-grid"><article class="panel evidence-box"><span class="kicker">WHAT IS WORKING</span><h3>Constructive evidence</h3>${list(good,'No material improving signal passed the documented threshold.')}</article><article class="panel evidence-box"><span class="kicker">WHAT IS WEAKENING</span><h3>Pressure points</h3>${list(weak,'No material weakening signal passed the documented threshold.')}</article><article class="panel evidence-box question"><span class="kicker">KEY CREDIT QUESTION</span><p>${esc(x.key_question)}</p></article></div><div class="chart-grid">${chartCard(x,'Revenue',p=>p.revenue,money)}${chartCard(x,'EBITDA proxy',p=>p.ebitda,money)}${chartCard(x,'Debt / EBITDA',p=>p.debt_ebitda,ratio)}${chartCard(x,'Interest coverage',p=>p.interest_coverage,ratio)}${chartCard(x,'Free cash flow',p=>p.free_cash_flow,money)}${chartCard(x,'Cash position',p=>p.cash,money)}</div>`;bindPicker($('#dossierContent'),renderDossier)}
function list(a,fallback){return `<ul>${(a.length?a:[fallback]).map(s=>`<li>${esc(s)}</li>`).join('')}</ul>`}
function chartCard(x,title,get,fmt){const rows=x.periods.filter(p=>get(p)!=null),W=420,H=160,pad=22;if(!rows.length)return `<article class="panel mini-chart"><span class="kicker">5-YEAR EVIDENCE</span><h3>${title}</h3><div class="empty">Unavailable in normalized filings</div></article>`;const vs=rows.map(get),min=Math.min(...vs,0),max=Math.max(...vs),span=max-min||1,pts=rows.map((r,i)=>[pad+i*(W-pad*2)/Math.max(rows.length-1,1),H-pad-(get(r)-min)/span*(H-pad*2)]),d=pts.map((q,i)=>`${i?'L':'M'}${q[0]},${q[1]}`).join(' ');return `<article class="panel mini-chart"><span class="kicker">5-YEAR EVIDENCE</span><h3>${title}</h3><svg viewBox="0 0 ${W} ${H}"><path class="area" d="${d} L${pts.at(-1)[0]},${H-pad} L${pts[0][0]},${H-pad}Z"/><path class="line" d="${d}"/>${pts.map((q,i)=>`<circle class="dot" cx="${q[0]}" cy="${q[1]}" r="3"/><text class="axis-label" x="${q[0]-12}" y="${H-4}">${rows[i].period.slice(0,4)}</text>`).join('')}</svg><footer>${fmt(vs.at(-1))} latest · source-linked SEC annual facts</footer></article>`}
function score(v,good,bad,invert=false){if(v==null)return 20;let s=Math.max(8,Math.min(100,(v-bad)/(good-bad)*100));return invert?100-s:s}
function renderMRI(){const x=state.selected;if(!x)return;const m=x.latest,rev=x.periods.length>1?(m.revenue-(x.periods.at(-2).revenue||m.revenue))/Math.abs(x.periods.at(-2).revenue||1):null,margin=m.revenue?m.ebitda/m.revenue:null,items=[['BUSINESS / OPERATING TREND',[['Revenue trend',rev,pct,score(rev,.12,-.1)],['EBITDA margin',margin,pct,score(margin,.3,.05)],['EBITDA stability',m.ebitda,money,m.ebitda&&m.ebitda>0?75:10],['FCF generation',m.free_cash_flow,money,m.free_cash_flow>0?75:15]]],['FINANCIAL',[['Leverage',m.debt_ebitda,ratio,score(m.debt_ebitda,6,1,true)],['Net leverage',m.net_debt_ebitda,ratio,score(m.net_debt_ebitda,5,0,true)],['Interest coverage',m.interest_coverage,ratio,score(m.interest_coverage,8,1)],['Debt trend',m.yoy_leverage,pct,score(m.yoy_leverage,.4,-.3,true)]]],['LIQUIDITY',[['Cash buffer',m.cash_debt,pct,score(m.cash_debt,.6,.05)],['Free cash flow',m.free_cash_flow,money,m.free_cash_flow>0?75:15],['FCF / Debt',m.fcf_debt,pct,score(m.fcf_debt,.25,-.05)],['Short-term debt',m.short_term_debt,money,m.short_term_debt==null?20:60]]],['MARKET CONTEXT',[['Equity signal',null,()=> 'Unavailable',20],['Valuation signal',null,()=> 'Unavailable',20],['Public filing recency',m.period,()=>m.period,90],['Source confidence',null,()=> 'SEC filed',92]]]];const arrows=x.signals.slice(0,5).map(s=>`${s.direction==='up'?'↑':'↓'} ${s.metric}`).join(' · ')||'→ No threshold-level directional signals';$('#mriContent').innerHTML=`<div class="mri-shell"><div class="mri-header"><div><h1 class="page-title">${x.ticker} / CREDIT MRI</h1><p>${esc(x.name)} · ${esc(x.sector)} · FY ${m.period}</p></div>${picker()}</div><div class="mri-grid">${items.map(([title,rows])=>`<section class="mri-column"><h3>${title}</h3>${rows.map(([label,v,fmt,s])=>`<div class="mri-row"><small><span>${label}</span><b>${fmt(v)}</b></small><div class="bar"><i style="width:${s}%"></i></div></div>`).join('')}</section>`).join('')}</div><div class="diagnosis"><div class="diagnosis-main"><h2>CREDLAB DIAGNOSIS / RESEARCH HEURISTIC</h2><strong>${x.trend==='STABLE'?'FUNDAMENTALS STABLE':`FUNDAMENTALS ${x.trend}`}</strong><div class="evidence-chain">${esc(arrows)}</div></div><div class="mri-question"><span class="kicker">KEY QUESTION</span><p>${esc(x.key_question)}</p></div></div></div>`;bindPicker($('#mriContent'),renderMRI)}
const presets={base:{growth:0,margin:0,interest:0,capex:0,debt:0,cash:0},bull:{growth:.08,margin:.02,interest:-.05,capex:0,debt:-.08,cash:.1},stress:{growth:-.1,margin:-.04,interest:.25,capex:.08,debt:.1,cash:-.2}};
function renderScenario(){const x=state.selected;if(!x)return;const m=x.latest,margin=m.revenue&&m.ebitda?m.ebitda/m.revenue:0;$('#scenarioContent').innerHTML=`<div class="issuer-head"><div><h1 class="page-title">Scenario Lab</h1><div class="issuer-meta"><b>${x.ticker} · ${esc(x.name)}</b><span>Base period ${m.period}</span></div></div>${picker()}</div><div class="scenario-layout"><aside class="panel controls"><span class="kicker">ASSUMPTION SET</span><h2>Operating & capital stress</h2><div class="presets"><button data-preset="base" class="active">BASE</button><button data-preset="bull">BULL</button><button data-preset="stress">STRESS</button></div>${control('growth','Revenue growth',-30,30,0,'%')}${control('margin','EBITDA margin change',-15,15,0,'pp')}${control('interest','Interest expense',-25,75,0,'%')}${control('capex','Capital expenditure',-25,50,0,'%')}${control('debt','Total debt',-25,50,0,'%')}${control('cash','Cash balance',-50,50,0,'%')}</aside><article class="panel scenario-results"><span class="kicker">BEFORE / AFTER</span><h2>Debt-service capacity</h2><div id="scenarioMetrics"></div></article></div>`;bindPicker($('#scenarioContent'),renderScenario);$$('.presets button').forEach(b=>b.onclick=()=>applyPreset(b.dataset.preset));$$('.control input').forEach(i=>i.oninput=calculateScenario);calculateScenario()}
function control(id,label,min,max,value,suffix){return `<div class="control"><label><span>${label}</span><b id="${id}Val">${value}${suffix}</b></label><input id="${id}" data-suffix="${suffix}" type="range" min="${min}" max="${max}" step="1" value="${value}"></div>`}
function applyPreset(name){$$('.presets button').forEach(b=>b.classList.toggle('active',b.dataset.preset===name));Object.entries(presets[name]).forEach(([k,v])=>$('#'+k).value=Math.round(v*100));calculateScenario()}
function calculateScenario(){const m=state.selected.latest;['growth','margin','interest','capex','debt','cash'].forEach(k=>$('#'+k+'Val').textContent=`${$('#'+k).value}${$('#'+k).dataset.suffix}`);const n=k=>+$('#'+k).value/100,rev=m.revenue==null?null:m.revenue*(1+n('growth')),ebitda=rev==null||m.ebitda==null?null:rev*((m.ebitda/m.revenue)+n('margin')),interest=m.interest_expense==null?null:m.interest_expense*(1+n('interest')),capex=m.capex==null?null:m.capex*(1+n('capex')),debt=m.total_debt==null?null:m.total_debt*(1+n('debt')),cash=m.cash==null?null:m.cash*(1+n('cash')),ocf=rev==null||m.operating_cash_flow==null?null:rev*(m.operating_cash_flow/m.revenue),fcf=ocf==null||capex==null?null:ocf-capex,out={ebitda,free_cash_flow:fcf,debt_ebitda:ebitda>0&&debt!=null?debt/ebitda:null,net_debt_ebitda:ebitda>0&&debt!=null&&cash!=null?(debt-cash)/ebitda:null,interest_coverage:interest>0&&ebitda!=null?ebitda/interest:null,fcf_debt:debt>0&&fcf!=null?fcf/debt:null};const comps=[['EBITDA',m.ebitda,out.ebitda,money],['Free cash flow',m.free_cash_flow,out.free_cash_flow,money],['Debt / EBITDA',m.debt_ebitda,out.debt_ebitda,ratio],['Net debt / EBITDA',m.net_debt_ebitda,out.net_debt_ebitda,ratio],['Interest coverage',m.interest_coverage,out.interest_coverage,ratio],['FCF / Debt',m.fcf_debt,out.fcf_debt,pct]];const worse=(out.debt_ebitda!=null&&m.debt_ebitda!=null&&out.debt_ebitda>m.debt_ebitda+.3)||(out.interest_coverage!=null&&m.interest_coverage!=null&&out.interest_coverage<m.interest_coverage*.8)||(out.free_cash_flow!=null&&out.free_cash_flow<0);$('#scenarioMetrics').innerHTML=`<div class="metric-comparison">${comps.map(([l,a,b,f])=>`<div class="comparison"><small>${l.toUpperCase()}</small><div class="values"><span class="old">${f(a)}</span><span class="arrow">→</span><span>${f(b)}</span></div></div>`).join('')}</div><div class="scenario-explain">${worse?'Under these assumptions, weaker debt-capacity metrics increase refinancing and deleveraging pressure.':'Under these assumptions, available debt-service metrics remain broadly resilient relative to the reported base period.'} Missing base facts remain N/A. This interpretation is generated only from the calculations shown above.</div>`}
boot();
